### ISSUE TITLE
Camera Pose Optimization

### ISSUE THREAD

**Issue by Gaozhongpai** [yifliu3/EndoGaussian#10]
Thanks for opening source this work.  May I ask if the current method can be used for endo videos with camera movements? During the training, does this method optimize the camera pose as well? Since if the initial poses from COLMAP may not be very accurate, the overall performance is not good. I notice that the EndoNeRF dataset's camera doesn't move but some other endo videos may have camera motions. Thanks again.

**Comment by yifliu3** [comment]
Thanks for your attention. The current method can be used with camera movements, and we have tested on the SCARED dataset, which consits  of static scenes with moving cameras. 

For the setting of the surgical reconstruction, we follow previous work to use the gt camera pose, thus the pose is not optimized like some SLAM of SfM methods. As the gt camera pose is provided by the dataset, we don't need to use COLMAP  to estimate the pose. And the initial points are generated by a direct re-projection (More details can refer to the paper).
