### ISSUE TITLE
why the same camera trajectories?

### ISSUE THREAD

**Issue by schwert26** [yifliu3/EndoGaussian#14]
Hello,

I hope this message finds you well. I have a question regarding the camera trajectories in ground truth and trained videos. Why are the camera trajectories identical between them? Is it possible to switch the camera perspectives? I've observed videos from other 3DGS where the output trajectory can be specified. I'm curious about this discrepancy and would appreciate any clarification you could provide.

Best regards.

**Comment by yifliu3** [comment]
Hi,
Thanks for your interest. For the EndoNeRF dataset, it is a single view point scene which means that the camera is fixed, and the scene  is dynamic. While for SCARED dataset, the camera is moving, and the scene is dynamic. Here we typically follow the setting of previous works.

**Comment by sunshinewuu** [comment]
Hi,
How can we observe the optimized Gaussians from any perspective or trajectories?

**Comment by yifliu3** [comment]
Hi, 

After optimizing, we can observe the Gaussians using any self-customized viewpoint. To achieve this, you can change the current video_cameras in the `endo_loader.py`, define the own camera viewpoint for each camera of video cameras, and call the render function. We may achieve this function in the future.

Another convenient way is to observe the reconstructed point cloud from `render.py`, where 3D softwares like MeshLab or Open3D can be easily used to control the viewpoint.

**Comment by sunshinewuu** [comment]
You've been incredibly helpful, thank you.And so sorry for my late response,I will try it later.
Thank you again!
