### ISSUE TITLE
Questions about Table1

### ISSUE THREAD

**Issue by cccrystalyang** [yifliu3/EndoGaussian#16]
How to calculate the results in Table 1? Is it after calculating the metrics for each scenario and then taking the average?

**Comment by yifliu3** [comment]
Hi, thanks for your attention.
Yes, the results are averaged for each input video sequence. For EndoNeRF, we average pulling and cutting. For SCARED dataset, we average d1k1, d2k1, d3k1, d6k1, and d7k1 following EndoSurf.

**Comment by cccrystalyang** [comment]
Thanks for your timely reply. Would you mind opening the evaluation metrics for each scenario for reproducibility?

**Comment by yifliu3** [comment]
Yes, of course. I will release the detailed results later when i return to the college.

You can also have a self try to check. I think the results would be close to the ones in the paper.

**Comment by cccrystalyang** [comment]
Thank you for the great work and I'll try it myself first.
