### ISSUE TITLE
I got images without rendering

### ISSUE THREAD

**Issue by MichaelWangGo** [yifliu3/EndoGaussian#17]
Hi authors,

Thanks for your excellent work!

I followed the instructions in README, but either for pulling or cutting, when I finished training the rendering results are black.

And when I tried to open the point cloud, it says NAN coords and 0 degenerated faces.
![pointcloud](https://github.com/yifliu3/EndoGaussian/assets/59171959/bdf5918e-187c-4a7d-9dc8-09b9be68f5bb)

Can you give me some suggestions?

**Comment by yifliu3** [comment]
Hi, thanks for your attention. 

I think the possible reason is rendered images are not converted to 0-255 froim 0-1 before saving, thus all saved values are 0. You can check this by printing the values right after the rendering. I'm wondering if you have followed `render.py` to get rendered images. 

Besides, can you observe normal psnr during the training? If so, the problem should not come from the rendering but from others.

**Comment by MichaelWangGo** [comment]
> Hi, thanks for your attention.
> 
> I think the possible reason is rendered images are not converted to 0-255 froim 0-1 before saving, thus all saved values are 0. You can check this by printing the values right after the rendering. I'm wondering if you have followed `render.py` to get rendered images.
> 
> Besides, can you observe normal psnr during the training? If so, the problem should not come from the rendering but from others.

Hi, thank you very much.

I print the rendering images, all pixels are 0., and yes I cannot see normal psnr during the training.

**Comment by yifliu3** [comment]
That's strange. I'm wondering if you have strictly followed the intruction in README.md. By the way, we tested our codes on Linux system, and I'm not sure if there is any problems with other systems like Windows.

**Comment by MichaelWangGo** [comment]
> That's strange. I'm wondering if you have strictly followed the intruction in README.md. By the way, we tested our codes on Linux system, and I'm not sure if there is any problems with other systems like Windows.

I run the code on linux system... but ok, let me double check the instructions. Thank you so much!

**Comment by MichaelWangGo** [comment]
Hi, I think the problem should be in the environment creation, the directory 'submodule/depth-diff-gaussian-rasterization/third_party' doesn't contain glm, so I git clone from here https://github.com/g-truc/glm/tree/5c46b9c07008ae65cb81ab79cd677ecc1934b903.

Except for this, I followed the instruction strictly.

**Comment by yifliu3** [comment]
Hi. The machines that we use may not have the glm originally. I have faced similar problems with glm on my machine and used `sudo apt-get install libglm-dev` instead of cloning and installing from source. Perhaps the problem comes from this.

**Comment by MichaelWangGo** [comment]
> Hi. The machines that we use may not have the glm originally. I have faced similar problems with glm on my machine and used `sudo apt-get install libglm-dev` instead of cloning and installing from source. Perhaps the problem comes from this.

That 's it! Problem solved after installing libglm-dev!

Thank you so much!!!

**Comment by fusheng-ji** [comment]
For who has no root authority to install libglm-dev with Linux machine, here is a practical solution:
You can clone the Gaussian-rasterizer submodule from [4dgaussian](https://github.com/hustvl/4DGaussians/tree/master/submodules) repo by command below. 
`git clone  --recursive https://github.com/ingra14m/depth-diff-gaussian-rasterization.git`
`pip install -e submodules/depth-diff-gaussian-rasterization`
Then the issue about point cloud and rendered images should be solved.
