### ISSUE TITLE
About the rendering images number

### ISSUE THREAD

**Issue by darthandvader** [yifliu3/EndoGaussian#19]
Hi, I found that the rendering number is based on the camera views from colmap, but the it is not matched with the number of training images. I wonder if you guys generated camera views of each frame or you did a train/test split somewhere. 
Thank you !

**Comment by yifliu3** [comment]
Hi, thanks for the attention. The rendering number is based on the training/testing split. We follow EndoSurf to get the dataset split. For example, we divide the pulling and cutting dataset into 8:1 training/testing split. You can find the detailed split strategy in the `EndoNeRF_Dataset` function of the `scene/endo_loader.py`

**Comment by darthandvader** [comment]
Thanks for your reply! 
 I'm also trying to figure out if you've ever tried converting the final shs back to RGB? Since the final SH would be n*16*3 and the SH2RGB function is linear which would only get 16*3 results.

**Comment by yifliu3** [comment]
Hi, the final SH (n*16*3) is features (the combination of colors and SH coefficients), thus can not be directly converted to RGB. 
Its (n*16*3)  function is mainly to participate in the rendering process to achieve view-dependent color modeling.
If you want to get pure RGB of 3D Gaussians, you can use the first 3 channels of features (n*3), and then convert to the color.
